### ISSUE TITLE
pyenv issue with missing /bin/libpython.dylib

### ISSUE THREAD

**Issue by martin-martin** [visini/pomodoro#1]
Hello! Thanks a lot for your article 🙌 .

- MacOS 10.15.3 (Catalina)
- Python 3.8.0 (via pyenv)
- pyenv 1.2.16

When attempting to create the standalone Pomodoro app from your repo with `python setup.py py2app`, I run into the following error:

```bash
----- py2app install output snipped off -----

copying file /Users/martin/project/path/venv/bin/python -> /Users/martin/project/path/dist/Pomodoro.app/Contents/MacOS/python
Traceback (most recent call last):
  File "setup.py", line 15, in <module>
    setup(
  File "/Users/martin/project/path/venv/lib/python3.8/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/Users/martin/.pyenv/versions/3.8.0/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/Users/martin/.pyenv/versions/3.8.0/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/Users/martin/.pyenv/versions/3.8.0/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/Users/martin/project/path/venv/lib/python3.8/site-packages/py2app/build_app.py", line 907, in run
    self._run()
  File "/Users/martin/project/path/venv/lib/python3.8/site-packages/py2app/build_app.py", line 1125, in _run
    self.run_normal()
  File "/Users/martin/project/path/venv/lib/python3.8/site-packages/py2app/build_app.py", line 1238, in run_normal
    self.create_binaries(py_files, pkgdirs, extensions, loader_files)
  File "/Users/martin/project/path/venv/lib/python3.8/site-packages/py2app/build_app.py", line 1619, in create_binaries
    mm.mm.run_file(runtime)
  File "/Users/martin/project/path/venv/lib/python3.8/site-packages/macholib/MachOGraph.py", line 89, in run_file
    raise ValueError("%r does not exist" % (pathname,))
ValueError: '/Users/martin/.pyenv/versions/3.8.0/lib/libpython3.8.dylib' does not exist
```

Do you have any idea or experience whether `pyenv` could be the culprit here, or is it Catalina?

**Comment by visini** [comment]
Can you try rebuilding CPython with enabling framework support? By default of CPython (and pyenv), the python executable will be generated as static linked and libpython*.dylib will not be generated.

`env PYTHON_CONFIGURE_OPTS="--enable-framework" pyenv install -v 3.8.0`

See here: https://github.com/pyenv/pyenv/issues/443#issuecomment-528277145

**Comment by martin-martin** [comment]
That worked (with installing `3.8.1`, the `.0` version maybe had some conflicts in knowing which one to select ¯\_(ツ)_/¯ 

```bash
env PYTHON_CONFIGURE_OPTS="--enable-framework" pyenv install -v 3.8.1
```

However, now I'm running into the [same issue](https://github.com/martin-martin/menu-bar-writing-prompts/issues/1) I did with my little app:

![Screenshot 2020-03-08 at 16 48 25](https://user-images.githubusercontent.com/12371494/76165148-58ecfb00-615d-11ea-8c9f-2cd096587d10.png)

Did you manage to run yours on Catalina? I assume that the new security measures might have introduced a problem here.

**Comment by visini** [comment]
My rumps apps all work fine on Catalina. Could be related to macOS gatekeeper. Can you try disabling gatekeeper? `sudo spctl --master-disable`

**Comment by visini** [comment]
> My rumps apps all work fine on Catalina. Could be related to macOS gatekeeper. Can you try disabling gatekeeper? `sudo spctl --master-disable`

Did this work?

**Comment by martin-martin** [comment]
Hi @visini thanks for your answer. Just tried running the command before starting the app, and it didn't change anything. Also tried to re-build it after disabling the gatekeeper (for good measure), but still the same result.

**Comment by janik6n** [comment]
@martin-martin Please have a look of my solution to an issue, which might be similar to yours: https://github.com/ronaldoussoren/py2app/issues/284

**Comment by martin-martin** [comment]
@janikarh yes! Your solution did it for me! Thanks so much 🎉

**Comment by visini** [comment]
Thank you @janikarh !
